# Site settings
title: "Technologieplauscherl"
email: organizers@technologieplauscherl.at
description: "Linzer Technologie Meetup - Mit Freunden zamkommen und Ã¼ber Technologie, Coding und Projekte reden"
keywords: "Technologie, Web, Java, CSS, HTML, JavaScript, Groovy, Grails, Meetup"
baseurl: ""
#url: "http://technologieplauscherl.at"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  sass_dir: _sass/
  style: compressed
gems:
- jekyll-sitemap

collections:
  community:
    permalink: :path/
  plauscherl:
    output: true
    permalink: /:name/
